version: 1.0.{build}
os: Visual Studio 2017
build:
  verbosity: minimal

branches:
  only:
    - master

build_script:
  - dotnet restore -r win10-x64
  - dotnet publish -c Release -r win10-x64
  - dotnet restore -r osx.10.12-x64
  - dotnet publish -c Release -rosx.10.12-x64

artifacts:
  - path: win10-x64
    name: Canopy.Cli.Executable\bin\Release\netcoreapp1.1\win10-x64
  - path: osx.10.12-x64
    name: Canopy.Cli.Executable\bin\Release\netcoreapp1.1\osx.10.12-x64

notifications:
  - provider: Slack
    auth_token:
      secure: 6JPs22qT50igyFG/AaVJAP4YnOcLEptYqXKF+5yC47SNA83YcikLBeGpA0CstoQqGLzUDiXdEPXuhaVpCL1bRA==
    channel: '#services'