version: 0.0.{build}
os: Visual Studio 2017
build:
  verbosity: minimal

branches:
  only:
    - master

build_script:
  - dotnet restore -r win10-x64
  - dotnet publish -c Release -r win10-x64
  - dotnet restore -r osx.10.12-x64
  - dotnet publish -c Release -r osx.10.12-x64
  - ps: |
      (Get-Content '.\canopy-cli.nuspec' -Raw).Replace("<version>0.0.0</version>", "<version>$($env:APPVEYOR_BUILD_VERSION)</version>") | Out-File '.\canopy-cli.nuspec'
      choco pack

artifacts:
  - path: Canopy.Cli.Executable\bin\Release\netcoreapp1.1\win10-x64\publish
    name: windows
  - path: Canopy.Cli.Executable\bin\Release\netcoreapp1.1\osx.10.12-x64\publish
    name: macos
  - path: .\canopy-cli.*.nupkg
    name: nupkg

notifications:
  - provider: Slack
    auth_token:
      secure: 6JPs22qT50igyFG/AaVJAP4YnOcLEptYqXKF+5yC47SNA83YcikLBeGpA0CstoQqGLzUDiXdEPXuhaVpCL1bRA==
    channel: '#services'

deploy:
  release: canopy-cli-v$(appveyor_build_version)
  description: 'Canopy Simulations Command Line Interface'
  provider: GitHub
  auth_token:
    secure: cHJ+kuG4xEMsSca6/+sT13XOrQMppwPbtPbFirijXcvJIpR4YjTeURw4xWghZkEk
  artifact: windows,macos,nupkg
  draft: false
  prerelease: false
  on:
    branch: master