version: 0.0.{build}
os: Visual Studio 2017
build:
  verbosity: minimal

branches:
  only:
    - master
    - /^v[0-9]+\.*/

assembly_info:
  patch: true
  file: AssemblyInfo.cs
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

init:
  # Set "build version number" to "short-commit-hash" or when tagged to "tag name" (Travis style)
  # https://github.com/appveyor/ci/issues/691
  - ps: >-
      if ($env:APPVEYOR_REPO_TAG -eq "true")
      {
        Update-AppveyorBuild -Version "$($env:APPVEYOR_REPO_TAG_NAME.TrimStart("v"))"
      }

build_script:
  - ps: |
      (Get-Content '.\Canopy.Cli.Shared\Canopy.Cli.Shared.csproj' -Raw).Replace("<Version>0.0.0</Version>", "<Version>$($env:APPVEYOR_BUILD_VERSION)</Version>") | Out-File '.\Canopy.Cli.Shared\Canopy.Cli.Shared.csproj'
      (Get-Content '.\Canopy.Cli.Shared\Canopy.Cli.Shared.csproj' -Raw).Replace("<AssemblyVersion>0.0.0.0</AssemblyVersion>", "<AssemblyVersion>$($env:APPVEYOR_BUILD_VERSION)</AssemblyVersion>") | Out-File '.\Canopy.Cli.Shared\Canopy.Cli.Shared.csproj'
      (Get-Content '.\Canopy.Cli.Shared\Canopy.Cli.Shared.csproj' -Raw).Replace("<FileVersion>0.0.0.0</FileVersion>", "<FileVersion>$($env:APPVEYOR_BUILD_VERSION)</FileVersion>") | Out-File '.\Canopy.Cli.Shared\Canopy.Cli.Shared.csproj'
  - msbuild ".\Canopy.Cli.Shared\Canopy.Cli.Shared.csproj"
  - mkdir "cli-shared-package"
  - copy ".\Canopy.Cli.Shared\bin\Release\Canopy.Cli.Shared.%APPVEYOR_BUILD_VERSION%.nupkg" "cli-shared-package"
  - dotnet restore -r win10-x64
  - dotnet publish -c Release -r win10-x64
  - dotnet restore -r osx.10.12-x64
  - dotnet publish -c Release -r osx.10.12-x64
  - ps: |
      (Get-Content '.\canopy-cli.nuspec' -Raw).Replace("<version>0.0.0</version>", "<version>$($env:APPVEYOR_BUILD_VERSION)</version>") | Out-File '.\canopy-cli.nuspec'
      choco pack
  
on_success:
 - appveyor PushArtifact ".\cli-shared-package\Canopy.Cli.Shared.%APPVEYOR_BUILD_VERSION%.nupkg"

artifacts:
  - path: Canopy.Cli.Executable\bin\Release\netcoreapp1.1\win10-x64\publish
    name: canopy-cli-windows
  - path: Canopy.Cli.Executable\bin\Release\netcoreapp1.1\osx.10.12-x64\publish
    name: canopy-cli-mac
  - path: .\canopy-cli.*.nupkg
    name: nupkg

notifications:
  - provider: Slack
    auth_token:
      secure: 6JPs22qT50igyFG/AaVJAP4YnOcLEptYqXKF+5yC47SNA83YcikLBeGpA0CstoQqGLzUDiXdEPXuhaVpCL1bRA==
    channel: '#services'

deploy:
  description: 'Canopy Simulations CLI release.'
  provider: GitHub
  auth_token:
    secure: cHJ+kuG4xEMsSca6/+sT13XOrQMppwPbtPbFirijXcvJIpR4YjTeURw4xWghZkEk
  artifact: canopy-cli-windows,canopy-cli-mac
  draft: false
  prerelease: false
  on:
    appveyor_repo_tag: true