version: 0.0.{build}
os: Visual Studio 2017
build:
  verbosity: minimal
  publish_nuget: true

branches:
  only:
    - master
    - /^v[0-9]+\.*/

init:
  # Set "build version number" to "short-commit-hash" or when tagged to "tag name" (Travis style)
  # https://github.com/appveyor/ci/issues/691
  - ps: >-
      if ($env:APPVEYOR_REPO_TAG -eq "true")
      {
        Update-AppveyorBuild -Version "$($env:APPVEYOR_REPO_TAG_NAME.TrimStart("v"))"
      }

build_script:
  - dotnet restore -r win10-x64
  - dotnet publish -c Release -r win10-x64
  - dotnet restore -r osx.10.12-x64
  - dotnet publish -c Release -r osx.10.12-x64
  - ps: |
      (Get-Content '.\canopy-cli.nuspec' -Raw).Replace("<version>0.0.0</version>", "<version>$($env:APPVEYOR_BUILD_VERSION)</version>") | Out-File '.\canopy-cli.nuspec'
      choco pack

artifacts:
  - path: Canopy.Cli.Executable\bin\Release\netcoreapp1.1\win10-x64\publish
    name: canopy-cli-windows
  - path: Canopy.Cli.Executable\bin\Release\netcoreapp1.1\osx.10.12-x64\publish
    name: canopy-cli-mac
  - path: .\canopy-cli.*.nupkg
    name: nupkg

notifications:
  - provider: Slack
    auth_token:
      secure: 6JPs22qT50igyFG/AaVJAP4YnOcLEptYqXKF+5yC47SNA83YcikLBeGpA0CstoQqGLzUDiXdEPXuhaVpCL1bRA==
    channel: '#services'

deploy:
  description: 'Canopy Simulations CLI release.'
  provider: GitHub
  auth_token:
    secure: cHJ+kuG4xEMsSca6/+sT13XOrQMppwPbtPbFirijXcvJIpR4YjTeURw4xWghZkEk
  artifact: canopy-cli-windows,canopy-cli-mac
  draft: false
  prerelease: false
  on:
    appveyor_repo_tag: true