# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  branches:
    include:
    - master
  tags:
    include:
    - v*

pool:
  vmImage: 'windows-latest'

variables:
  major: 0
  # Define a counter to continue on from AppVeyor.
  minor: $[counter(variables.major, 87)]
  buildVersion: $[format('{0}.{1}.0', variables.major, variables.minor)]

name: $(buildVersion)

steps:
- task: UseDotNet@2
    inputs:
    packageType: 'sdk'
    version: '5.x'

- powershell: |
    $tags = git tag --sort=-creatordate
    $releaseBuildVersion = $tags[0].TrimStart("v")
    echo "##vso[task.setvariable variable=buildVersion]$releaseBuildVersion"
  condition: startsWith(variables['Build.SourceBranch'], 'refs/tags/')
  displayName: 'Set release version'

- powershell: |
    Write-Host "Release Version: $env:BUILDVERSION"
    (Get-Content '.\Canopy.Cli.Shared\Canopy.Cli.Shared.csproj' -Raw).Replace("<Version>0.0.0</Version>", "<Version>$($env:BUILDVERSION)</Version>") | Out-File '.\Canopy.Cli.Shared\Canopy.Cli.Shared.csproj'
    (Get-Content '.\Canopy.Cli.Shared\Canopy.Cli.Shared.csproj' -Raw).Replace("<AssemblyVersion>0.0.0.0</AssemblyVersion>", "<AssemblyVersion>$($env:BUILDVERSION)</AssemblyVersion>") | Out-File '.\Canopy.Cli.Shared\Canopy.Cli.Shared.csproj'
    (Get-Content '.\Canopy.Cli.Shared\Canopy.Cli.Shared.csproj' -Raw).Replace("<FileVersion>0.0.0.0</FileVersion>", "<FileVersion>$($env:BUILDVERSION)</FileVersion>") | Out-File '.\Canopy.Cli.Shared\Canopy.Cli.Shared.csproj'
  displayName: 'Update release version in files'

- powershell: |
    Write-Host "Building nupkg"
    dotnet restore ".\Canopy.Cli.Shared\Canopy.Cli.Shared.csproj"
    dotnet build -c Release .\Canopy.Cli.Shared\Canopy.Cli.Shared.csproj
    dotnet publish -c Release .\Canopy.Cli.Shared\Canopy.Cli.Shared.csproj
    $packageSource = "$env:BUILD_SOURCESDIRECTORY\Canopy.Cli.Shared\bin\Release\Canopy.Cli.Shared.$($env:BUILDVERSION).nupkg"
    $packageTarget = "$env:BUILD_ARTIFACTSTAGINGDIRECTORY"
    Write-Host "Copying $packageSource to $packageTarget"
    copy "$packageSource" "$packageTarget"

    Write-Host "Building Windows"
    dotnet restore -r win10-x64
    dotnet build -c Release -r win10-x64
    dotnet publish -c Release -r win10-x64

    Write-Host "Building OSX"
    dotnet restore -r osx.10.12-x64
    dotnet build -c Release -r osx.10.12-x64
    dotnet publish -c Release -r osx.10.12-x64
  displayName: 'dotnet build'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.SourcesDirectory)/Canopy.Cli.Executable\bin\Release\net5.0\win10-x64\publish'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/canopy-cli-windows.zip'
    replaceExistingArchive: true

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.SourcesDirectory)/Canopy.Cli.Executable\bin\Release\net5.0\osx.10.12-x64\publish'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/canopy-cli-mac.zip'
    replaceExistingArchive: true
    
- task: NuGetCommand@2
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: '20d08566-c42a-44c8-b627-3f221476c5c4'
    
- task: NuGetCommand@2
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: '156d67a5-e250-4ecf-bbe2-086bde6e26c2/7705f740-1dee-41d0-ac4d-15e2db94bc0a'

- task: GitHubRelease@1
  condition: startsWith(variables['Build.SourceBranch'], 'refs/tags/')
  inputs:
    gitHubConnection: 'Git PAT'
    repositoryName: '$(Build.Repository.Name)'
    action: 'create'
    target: '$(Build.SourceVersion)'
    tagSource: 'gitTag'
    tagPattern: 'v.*'
    releaseNotesSource: 'inline'
    releaseNotesInline: 'Canopy Simulations CLI release.'
    addChangeLog: false
